spring:
  application:
    name: ingsis
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

#azure:
#  storage:
#    connection-string: DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_ACCOUNT_KEY};BlobEndpoint=${AZURE_STORAGE_BLOB_ENDPOINT}

server:
  port: 8081
  address: 0.0.0.0

redis:
  streams:
    formatRequest: ${REDIS_STREAM_REQUEST_FORMAT_KEY}
    formatResult: ${REDIS_STREAM_RESULT_FORMAT_KEY}
  groups:
    format: ${REDIS_GROUP_FORMAT_KEY}